fail_fast: false
repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: nix develop -c cargo fmt --all --
        language: system
        types: [rust]
        pass_filenames: false

      - id: cargo-clippy
        name: cargo clippy
        entry: nix develop -c cargo clippy --all-targets --all-features -- -D warnings
        language: system
        types: [rust]
        pass_filenames: false

      - id: cargo-test
        name: cargo test
        entry: nix develop -c cargo test --all
        language: system
        types: [rust]
        pass_filenames: false
        stages: [pre-push]

      - id: nixpkgs-fmt
        name: nixpkgs-fmt
        entry: nix develop -c nixpkgs-fmt
        language: system
        types: [nix]
